### ISSUE TITLE
Add global borrow pause override to comptroller

### ISSUE THREAD

**Issue by sriyantra** [Rari-Capital/fuse-v1#25]
Option for reopening fuse pools

**Comment by sriyantra** [comment]
https://github.com/Rari-Capital/fuse-v1/tree/feature/global-pause-borrows-override

**Comment by sriyantra** [comment]
@zerosnacks please review. We just need to ensure no state corruption upon upgrade

**Comment by zerosnacks** [comment]
Reviewed, left some minor comments. I was a bit confused at first.

Is there a recommended way we could verify that this does not cause state corruption?

Perhaps a mainnet fork and then a Hardhat deployment script with basic verification checks?

**Comment by sriyantra** [comment]
could really just do a foundry deployment with simple checks. But yea this shouldn't alter state in any way
