### ISSUE TITLE
Add deployment / verification flow

### ISSUE THREAD

**Issue by sriyantra** [Rari-Capital/fuse-v1#27]

**Comment by sriyantra** [comment]
1st try at a config file https://github.com/Rari-Capital/fuse-v1/blob/feat/hardhat-config-v1/hardhat.config.ts

**Comment by zerosnacks** [comment]
WIP branch here: https://github.com/Rari-Capital/fuse-v1/pull/36

**Comment by zerosnacks** [comment]
Perhaps there are some basic tests we can port from https://github.com/Rari-Capital/rari-capital-hardhat?

**Comment by zerosnacks** [comment]
This was just released, perhaps there are things in there we can borrow? 
https://github.com/foundry-rs/hardhat-foundry-template

**Comment by zerosnacks** [comment]
> This was just released, perhaps there are things in there we can borrow? https://github.com/foundry-rs/hardhat-foundry-template

Closed in #36 

May enhance it with small changes in the future based on the above mentioned template

**Comment by zerosnacks** [comment]
Re-opening this ticket to keep track of the deployment / verifaction flow scripts

**Comment by zerosnacks** [comment]
Foundry scripting and deployments landed https://twitter.com/gakonst/status/1531056739470016512

For now lets stick with our dual Hardhat / Foundry setup but interesting for the longer term

**Comment by zerosnacks** [comment]
I think we can add this as part of another PR when we feel like we have an update that requires a deployment / verification flow
