### ISSUE TITLE
Clarify if the Fuse V1 codebase encapsulates all Fuse contracts that are live in production and what to test

### ISSUE THREAD

**Issue by zerosnacks** [Rari-Capital/fuse-v1#38]
As it stands the current codebase of `fuse-v1` contains:
- `compound-protocol` fork, branch `fuse-reactive-audit` and `fuse-plugin-4626` 
- `fuse-contracts`, branch `v1.2.3`

@sriyantra please correct me if I'm wrong or if we are missing any code that is live in production and is part of Fuse.

It is not exactly clear to me whether `fuse-flywheel` should be part of `fuse-v1`.

I think our emphasis of the tests we write should focus on getting 100% coverage on the diff between the `master` branch of Compound Protocol and this codebase + integration tests (mainnet fork) + deployment tests (simulating upgrades, making sure no state corrupts).

We need to evaluate whether it makes sense to import the Compound Protocol test suite as it includes a ton of tech debt. On the other hand without it it becomes hard to get a footing. Does it make sense to port the Midas Protocol test suite? I think it does to a degree but the diff between our codebases is quite large and they changed a lot of subtle things.

I would also like to align with front-end and devops about how `fuse-v1` can support them (abi generation, deployment scripts, etc..) because I want to avoid duplicating efforts (as in, should `fuse v1` cover deployment tests if devops already has written a test suite?)

We should also evaluate whether the upcoming external audit should happen on this codebase and determine what they require from us to be there so they can spend their auditing time effectively.

**Comment by sriyantra** [comment]
Flywheel is in production use (such as pool 156 as a rewards distributor) but I don't see it as a priority for testing. It's a small surface area anyway covering just rewards

For tests, I'm not that interested in porting Compound Protocol tests. I would prefer to port the Midas Protocol tests, but I would like to hear how much work you think that would be. Consider our production blockers for migrating to similar contracts to Midas: the regular front-end deployment flow of comptrollers and ctokens.

We can schedule a meeting with front-end to discuss what is possible with some of the changes
