### ISSUE TITLE
Evaluate if the latest version of deployed contracts match the changes made in the codebase

### ISSUE THREAD

**Issue by zerosnacks** [Rari-Capital/fuse-v1#48]
A clear example is `RewardsDistributorDelegate` having a `pragma solidity ^0.5.16;` on the deployed version (https://etherscan.io/address/0x220f93183a69d1598e8405310cb361cff504146f) and `pragma solidity 0.5.17;` in our codebase. Whilst very minor - our goal for now is to have a 1:1 representation of the current state of production so I think we should downgrade the version in our codebase to match production.

**Comment by sriyantra** [comment]
point taken but basically the entire codebase has been switched to `0.5.17.` I would rather keep it there especially in the case of future modifications and deployments
