### ISSUE TITLE
Publicly archive our compound-protocol fork and fuse-contracts repositories

### ISSUE THREAD

**Issue by zerosnacks** [Rari-Capital/fuse-v1#49]
All development regarding Fuse should happen inside of this repository going forward.
I suggest archiving the repositories because it is not clear yet to the outside world we have made that decision.

https://github.com/rari-Capital/fuse-contracts

https://github.com/Rari-Capital/compound-protocol

**Comment by zerosnacks** [comment]
We will have to evaluate whether to make `fuse-contracts` a private archive

**Comment by sriyantra** [comment]
> We will have to evaluate whether to make `fuse-contracts` a private archive

`fuse-contracts` is already public in this repo though. Also all of the oracles are verified on etherscan. I see no reason to make it private again

**Comment by sriyantra** [comment]
I've now archived the 2 mentioned repos
